name: teamproject_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/tree.jpg
    - lib/assets/image/Cat_nomoney.png
    - lib/assets/background.jpg
    - lib/assets/image/LG.png
    - lib/assets/image/profile_pic.png
