// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTbvH5m_fdrBdowXOCbLR6zulCxRb3A4',
    appId: '1:25224739336:web:618acedcb6ebe4f1eeefbd',
    messagingSenderId: '25224739336',
    projectId: 'sample-firebase-ai-app-67e18',
    authDomain: 'sample-firebase-ai-app-67e18.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-67e18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt5wxNAU3Ohhb8ERHp2KQvzfwuRYz6aFw',
    appId: '1:25224739336:android:c7d36ff18268e8dceeefbd',
    messagingSenderId: '25224739336',
    projectId: 'sample-firebase-ai-app-67e18',
    storageBucket: 'sample-firebase-ai-app-67e18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKk71P1BIQCXAE5Yf2jCN8_44acAtMpMI',
    appId: '1:25224739336:ios:8231182100dffc52eeefbd',
    messagingSenderId: '25224739336',
    projectId: 'sample-firebase-ai-app-67e18',
    storageBucket: 'sample-firebase-ai-app-67e18.appspot.com',
    iosBundleId: 'com.example.teamproject3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKk71P1BIQCXAE5Yf2jCN8_44acAtMpMI',
    appId: '1:25224739336:ios:8231182100dffc52eeefbd',
    messagingSenderId: '25224739336',
    projectId: 'sample-firebase-ai-app-67e18',
    storageBucket: 'sample-firebase-ai-app-67e18.appspot.com',
    iosBundleId: 'com.example.teamproject3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxTbvH5m_fdrBdowXOCbLR6zulCxRb3A4',
    appId: '1:25224739336:web:f59fb24b753a2e73eeefbd',
    messagingSenderId: '25224739336',
    projectId: 'sample-firebase-ai-app-67e18',
    authDomain: 'sample-firebase-ai-app-67e18.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-67e18.appspot.com',
  );
}
